version: "3.8"
services:
  auth-service:
    build: ./
    command: ./app
    ports:
      - 8050:8050
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medods_auth