env: "local" # local, dev, prod
auth_db:
  host: localhost #ignored if used by docker
  port:
  user: postgres
  password: postgres
  name: medods_auth
  sslmode: disable
auth_server:
  host: localhost
  port: 8050